name = "Fren Modpack"
author = "John Benber"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaed40f0d404a5f68bd340b37dca821e159e5be0e90cb8240629e1608bee0247"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
